// <auto-generated />
using DataCallingFirefighters.InfrastructureServices.Gateways.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataCallingFirefighters.WebService.Migrations
{
    [DbContext(typeof(DutaCallingFirefighter))]
    [Migration("20200526174027_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("DataCallingFirefighters.DomainObjects.DataCallingFirefighter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("Month")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberOfCalls")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataCallingFirefighters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            District = "Северный Административный округ",
                            Month = "Январь",
                            NumberOfCalls = "408",
                            Year = "2015"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
